name: gallery
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  cupertino_icons: ^0.1.2
  rally_assets: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/cupertino/
    - assets/icons/material/
    - assets/icons/reference/
    - assets/icons/shrine_card/
    - packages/rally_assets/logo.png
    - packages/rally_assets/thumb.png
    - assets/crane/flights/
    - assets/crane/

  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-SemiBold.ttf
          weight: 600
        - asset: fonts/Oswald-Medium.ttf
          weight: 500
    - family: Roboto Condensed
      fonts:
        - asset: packages/rally_assets/RobotoCondensed-Light.ttf
          weight: 400
        - asset: packages/rally_assets/RobotoCondensed-Regular.ttf
          weight: 500
        - asset: packages/rally_assets/RobotoCondensed-Bold.ttf
          weight: 700
    - family: Eczar
      fonts:
        - asset: packages/rally_assets/Eczar-Regular.ttf
          weight: 400
        - asset: packages/rally_assets/Eczar-SemiBold.ttf
          weight: 600
        - asset: packages/rally_assets/Eczar-Bold.ttf
          weight: 700
    # Crane font
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
